from PyQt5.QtWidgets import*

app = QApplication([])
window = QWidget()
window.resize(900, 700)

armature = QLabel("Список заміток")
bulochka = QLabel("Список тегів")
textplace = QTextEdit()
textsearch = QLineEdit()
Napoleon0 = QPushButton("Створити замітку")
Napoleon1 = QPushButton("Видалити замітку")
Napoleon2 = QPushButton("Зберегти замітку")
Napoleon3 = QPushButton("Додати до замітки")
Napoleon4 = QPushButton("Відкріпити від замітки")
Napoleon5 = QPushButton("Шукати замітки по тегу")
algebra = QListWidget()
geometrydash = QListWidget()

mainline = QHBoxLayout()
line1 = QVBoxLayout()
line2 = QVBoxLayout()
lineer1 = QHBoxLayout()
lineer2 = QHBoxLayout()

mainline.addLayout(line1)
mainline.addLayout(line2)

line1.addWidget(textplace)
line2.addWidget(armature)
line2.addWidget(algebra)
lineer1.addWidget(Napoleon0)
lineer1.addWidget(Napoleon1)
line2.addLayout(lineer1)
line2.addWidget(Napoleon2)
line2.addWidget(bulochka)
line2.addWidget(geometrydash)
line2.addWidget(textsearch)
lineer2.addWidget(Napoleon3)
lineer2.addWidget(Napoleon4)
line2.addLayout(lineer2)
line2.addWidget(Napoleon5)
window.setLayout(mainline)

window.show()
app.exec()